/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2017 NEM
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

import * as nemSdk from "nem-sdk";
import * as CryptoJS from 'crypto-js';
import {Password} from "../models/wallet/Password";
import {Wallet} from "../models/wallet/Wallet";
import {NetworkTypes} from "../models/node/NetworkTypes";
import get_random_values = require("get-random-values");
import {Address} from "../models/account/Address";
import {TransferTransaction} from "../models/transaction/TransferTransaction";
import {TimeWindow} from "../models/transaction/TimeWindow";
import {XEM} from "../models/mosaic/XEM";
import {PlainMessage} from "../models/transaction/PlainMessage";

export interface QRWalletText {
  type: number;
  v: number;
  data: {
    name: string,
    priv_key: string,
    salt: string
  }
}

export interface QRAddressText {
  type: number;
  v: number;
  data: {
    addr: string,
    name: string
  }
}

export interface QRTransactionText {
  type: number;
  v: number;
  data: {
    addr: string,
    amount: number,
    msg: string
  }
}

export class QRService {

  /**
   * Generates the QR text from the wallet
   * @returns {string}
   */
  generateWalletQRText(password: Password, wallet: Wallet): string {
    // Decrypt/generate private key and check it. Returned private key is contained into this.common
    let privateKey = wallet.unlockPrivateKey(password);

    let mobileKeys = this.AES_PBKF2_encryption(password, privateKey);

    let QR = {
      "v": wallet.network == NetworkTypes.TEST_NET ? 1 : 2,
      "type": 3,
      "data": {
        "name": wallet.name,
        "priv_key": mobileKeys.encrypted,
        "salt": mobileKeys.salt
      }
    };

    return JSON.stringify(QR);
  }

  /**
   * Decrypt the private key from the QR text
   * @param password password
   * @param qrWalletText Object generated by generateWalletQRText method
   * @return Decrypted private key
   */
  decryptWalletQRText(password: Password, qrWalletText: QRWalletText): string {
    let encryptedData = qrWalletText.data;
    let salt = CryptoJS.enc.Hex.parse(encryptedData.salt);
    let encrypted = encryptedData.priv_key;

    //generate key
    let key = CryptoJS.PBKDF2(password.value, salt, {
      keySize: 256 / 32,
      iterations: 2000
    }).toString();

    //separated from priv_key iv and cipherdata
    let iv = encrypted.substring(0, 32);
    let encryptedPrvKey = encrypted.substring(32, 128);

    //separated  vh from priv_key iv and cipherdata
    let obj = {
      ciphertext: CryptoJS.enc.Hex.parse(encryptedPrvKey),
      iv: nemSdk.default.utils.convert.hex2ua(iv),
      key: nemSdk.default.utils.convert.hex2ua(key.toString())
    };
    const decrypt = nemSdk.default.crypto.helpers.decrypt(obj);
    if (decrypt === "" || (decrypt.length != 64 && decrypt.length != 66)) throw new Error("invalid password");
    return decrypt;
  }

  /**
   * Generates the QR text from an address
   * @returns {string}
   */
  generateAddressQRText(address: Address): string {
    let QR = <QRAddressText>{
      "v": address.network() == NetworkTypes.TEST_NET ? 1 : 2,
      "type": 1,
      "data": {
        "addr": address.plain(),
        "name": "wallet"
      }
    };

    return JSON.stringify(QR);
  }

  /**
   * Decrypt the address from the QR text
   * @param qrAddressText Object generated by generateAddressQRText method
   * @return Address
   */
  decryptAddressQRText(qrAddressText: QRAddressText): Address {
    return new Address(qrAddressText.data.addr);
  }

  /**
   * Generates the QR text from a transaction
   * @returns {string}
   */
  generateTransactionQRText(recipientAddress: Address, amount: number, msg: string): string {
    let QR = <QRTransactionText>{
      "v": recipientAddress.network() == NetworkTypes.TEST_NET ? 1 : 2,
      "type": 2,
      "data": {
        "addr": recipientAddress.plain(),
        "amount": amount,
        "msg": msg
      }
    };

    return JSON.stringify(QR);
  }

  /**
   * Decrypt the transaction from the QR text
   * @param qrTransactionText Object generated by generateTransactionQRText method
   * @return TransferTransaction
   */
  decryptTrasactionQRText(qrTransactionText: QRTransactionText): TransferTransaction {
    return TransferTransaction.create(
      TimeWindow.createWithDeadline(),
      new Address(qrTransactionText.data.addr),
      new XEM(qrTransactionText.data.amount),
      PlainMessage.create(qrTransactionText.data.msg)
    );
  }

  /**
   * @internal
   * @param password
   * @param privateKey
   */
  private AES_PBKF2_encryption(password: Password, privateKey: string) {
    let salt = CryptoJS.lib.WordArray.random(256 / 8);
    let key = CryptoJS.PBKDF2(password.value, salt, {
      keySize: 256 / 32,
      iterations: 2000
    });
    let iv = new Uint8Array(16);
    get_random_values(iv);
    let encIv = {
      iv: nemSdk.default.utils.convert.ua2words(iv, 16)
    };
    let encrypted = CryptoJS.AES.encrypt(CryptoJS.enc.Hex.parse(privateKey), key, encIv);
    return {
      encrypted: nemSdk.default.utils.convert.ua2hex(iv) + encrypted.ciphertext,
      salt: salt.toString()
    }
  }

}